### ISSUE TITLE
big push issue

### ISSUE THREAD

**Issue by dreymoreau** [torontojs/blog#18]
Marco Tasks:
- [x] AuthorCard (Components)
- [x] Avatar (Components)
- [x] PostHeader (Components)
- [x] RefreshBanner (Components)
- [x] SkipToContent (Components)
- [x] TagList (Components)
- [x] HomeMain (Components)
- [x] accessibility (Pages)
- [x] license (Pages)
- [x] remove offline page

drey Tasks:
- [x] switch blog route to home
- [x] PageHeader (Components)
- [x] PageFooter (Components)
- [x] SiteNav (Components)
- [x] SiteFooter (Components)
- [x] codeofc (link to main torontojs website codeofc)
- [x] report (Pages) link to report page
- [x] add svg to siteNav component and update about page 
- [x] about (Pages)
- [x] finalize author write up ++ add photo

both of us:
- [x] BlogPosts Styling (Base)
- [x] PostCard (Components)
- [x] PostCardSmall (Components)
- [x] style authors page
- [x] update discord invite link
- [x] do final check up of blog, breakpoints, weird stuff

**Comment by madcampos** [comment]
Not to be _pushy_ or anything...

**Comment by dreymoreau** [comment]
CLOSING! wow. proud of us pal!! onto to the next chapter
