### ISSUE TITLE
Add pronouns field for the author metadata

### ISSUE THREAD

**Issue by madcampos** [torontojs/blog#46]
To make the blog more inclusive we want to add a pronouns field to the [authors schema](https://github.com/torontojs/blog/blob/main/src/schemas/authors.ts), and also make it optional, so people only provide this information if they are confortable.

We should also add this information to the ["how to add an author"](https://github.com/torontojs/blog/blob/main/src/content/docs/adding-authors.md) docs.

**Comment by dreymoreau** [comment]
lets just do this

**Comment by madcampos** [comment]
@evert yes, this is done, will close the issue. Thank you for flagging!
