### ISSUE TITLE
Combine `PostCard` and `PostCardSmall` into a single component

### ISSUE THREAD

**Issue by madcampos** [torontojs/blog#48]
Both components are very similar and only change in layout, it would be nice to combine them into a single component using container queries so they change in layout only based on the size they are in.

Another option would be to add an optional prop to specify the size, but that should be a fallback if the container queries solution doesn't work out.

**Comment by heem42** [comment]
From my understanding, PostCard is used for showing the list of Posts on main page whereas PostCardSmall is used to show any related Posts at the bottom of BlogPost. Some points that came in my mind which are making me think that these two components might not be good candidates for a merge.

- Both are used on different pages, serving slightly different purpose (one having extra detail) and considering that PostCard is the main component to show, and will be having changes in future, things might get complex if we merge them into one.
- They have a different layout and use couple of different elements. We'll be having more complex single component
- Even tho, they have common props but PostCard takes 3 extra props. We'll be passing extra data in case of PostCardSmall. 

I think changing the name of PostCardSmall to something like RelatedPostCard distinguish it better. What do you think?

**Comment by madcampos** [comment]
The point about layout is not an issue if we use container queries. The markup is very similar and could benefit from having a common format and not diverging.

But indeed, the two are slightly different, so I don't know if we should merge or not...

One option is to abstract the difference away and have a `<slot>` for the extra details. That way we have a post card that is generic enough to fill both places and can extend it to add entry points for extra details.

**Comment by madcampos** [comment]
Closed by #61
