### ISSUE TITLE
Display social media links on author page

### ISSUE THREAD

**Issue by madcampos** [torontojs/blog#49]
The [author page](https://github.com/torontojs/blog/blob/main/src/pages/authors/%5Bauthor%5D.astro) already references the [author schema](https://github.com/torontojs/blog/blob/main/src/schemas/authors.ts), but we don't add social media links to that page.

It would be nice to add a list of links with the author's social media links.

**Comment by dreymoreau** [comment]
OUUU YA,, i was literally thinking about this the other day when i was showing someone,, like hehehe secret link .... O,, ya but it doesnt go anywhere when u click on the faces >3< >3< maybe something we tackle together ?? AHA
